### ISSUE TITLE
Where to provide credential for private host

### ISSUE THREAD

**Issue by lli-hiya** [virtuald/docker-registry-cache#13]
From the README I cannot see anywhere credential is mentioned. However, my use case is that I would like this cache to pull from our private artifactory if the artifact is not locally stored, which requires authentication. 

Also, how is this cache different from https://github.com/docker/docker.github.io/blob/master/registry/deploying.md, which could also be configured as a pull-through cache.

**Comment by virtuald** [comment]
Someone added passthru basic auth support in #7... I suppose we should add something to the readme documenting that. In theory it should 'just work' without any configuration required.

The document you referenced mentions nothing about a pull-through cache. When this repo was created two years ago, the docker registry server only supported pull-through from docker hub, and not from private registries. If that has changed, then this repository is no longer useful.
