### ISSUE TITLE
qs

### ISSUE THREAD

**Issue by mg03** [virtuald/docker-registry-cache#2]
Scenario: docker private hub is called docker.private.com and the cache is given dns name dockercache.private.com

So all containers to be pushed to the hub will be tagged like

docker.private.com/mycontainer:latest

When I pull from the cache

do I pull as 

docker.private.com/mycontainer:latest

or 

dockercache.private.com/mycontainer:latest

**Comment by virtuald** [comment]
The second: dockercache.private.com/mycontainer:latest
