### ISSUE TITLE
Staleness

### ISSUE THREAD

**Issue by scottillogical** [virtuald/docker-registry-cache#4]
When you update a docker image tag, like "latest", does this cache result in a stale result?

**Comment by virtuald** [comment]
I feel like I tried that when I created this, and that the metadata isn't actually cached, just the giant blobs -- unfortunately I no longer have an installation of this available for me to test with, so I can't verify this myself.

The docker v2 registry was designed with HTTP caching in mind, and there really wasn't any extra configuration required to tell squid to force it to cache things, so I would imagine that it deals with the problem correctly. Try it out and let me know.

**Comment by virtuald** [comment]
I assume this works, let me know if that isn't the case!
