### ISSUE TITLE
Will Mutil pulls for same image cause File synchronization problem?

### ISSUE THREAD

**Issue by duyanghao** [virtuald/docker-registry-cache#5]
considering this situation:
the image A is being pulled by two docker daemon at the same time,will file synchronization problem(writing the same file) happen in this situation?

**Comment by virtuald** [comment]
This is just a project that configures squid. Assuming that docker registry and squid are consistent... then the answer should be yes. If they aren't, I recommend filing a bug in one of those two projects, as there's not much that can be done here for it.

**Comment by duyanghao** [comment]
the problem above(about file synchronization) is related to squid instead of registry,i will figure it out by myself :)

**Comment by virtuald** [comment]
If you figure out a way to address the issue, feel free to comment here or put a PR to update the documentation so that others won't have to deal with that in the future. :)

**Comment by Rid** [comment]
For anyone else looking for a solution to a cache miss storm, you can enable collapsed forwarding:

https://wiki.squid-cache.org/Features/CollapsedForwarding
