### ISSUE TITLE
Basic Auth issues through proxy

### ISSUE THREAD

**Issue by hulu1522** [virtuald/docker-registry-cache#6]
It seems that we cannot do `docker login` through the squid proxy.  Is this a known issue or is there extra configurations that are needed to allow this functionality.  Seems like authentication would be important to allow.  Thanks.

**Comment by virtuald** [comment]
When I was using this, we didn't have authentication on our registry, so I've never tried it. I'm sure there's a way to make it work though... please let me know what you find and I can update the documentation for others.

**Comment by virtuald** [comment]
Ah yes, someone else had issues with this too, but they never got back to me to document it: https://github.com/virtuald/docker-registry-cache/issues/1

It does look like squid supports authentication if you configure it. Would just need a good way to do so.

**Comment by hulu1522** [comment]
@virtuald I have tested PR #7  and seems to work just fine.  We even authenticate to artifactory and I can share what is needed there if you want that also.

**Comment by virtuald** [comment]
If it's a generally useful thing to add to the docs, sure. Thanks!
