### ISSUE TITLE
Question: What is the issue with v1?

### ISSUE THREAD

**Issue by tehlers320** [virtuald/docker-registry-cache#9]
The pulls are working for me with a v1 repo? Is there some other issue?

**Comment by tehlers320** [comment]
Ahhh.. you know what. Docker-trusted-registry 1.x seems to have the /v2 api? So i'm a little confused there. Maybe that's the issue.

**Comment by virtuald** [comment]
Yeah, v1/v2 refers to the docker remote API version.
